# sudo: required

# language: bash

env:
  global:
    - APP=gatsby
    - APP_FOLDER=Gatsby

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  provider: s3
  access_key_id:
    secure: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "eu-central-1"
  skip_cleanup: true
  bucket: "oliver-goetz-capstone-bucket"
  local_dir: ./App/$APP_FOLDER/public
