sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t trooper1989/gatsby-app -f ./App/Gatsby/Dockerfile.dev ./App/Gatsby

script:
  - docker run -e CI=true trooper1989/gatsby-app npm test

before_deploy:
  - echo 'Zipping the app'
  - cd ./App/app && zip -r /$TRAVIS_BUILD_DIR/gatsby-app-$TRAVIS_BUILD_NUMBER.zip *
  - echo 'Zipping finished'

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "eu-central-1"
  app: "docker-app"
  env: "docker-app-env"
  zip_file: /$TRAVIS_BUILD_DIR/docker-app-$TRAVIS_BUILD_NUMBER.zip
  skip_cleanup: true
  bucket_name: "elasticbeanstalk-eu-central-1-451453809844"
