sudo: required
services:
  - docker

before_install:
  - docker build -t trooper1989/react-uni -f ./App/app/Dockerfile.dev ./App/app

script:
  - docker run -e CI=true trooper1989/react-uni npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "eu-central-1"
  app: "docker-app"
  env: "docker-app"
  bucket_name: "oliver-goetz-docker"
