sudo: required
language: bash
services:
  - docker

before_install:
  - echo 'Zipping the app'

  - zip -r $TRAVIS_BUILD_DIR/docker-app-$TRAVIS_BUILD_NUMBER.zip ./App/app
  - echo 'Zipping finished'
  - docker build -t trooper1989/react-uni -f ./App/app/Dockerfile.dev ./App/app

script:
  - docker run -e CI=true trooper1989/react-uni npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "eu-central-1"
  app: "docker-app"
  env: "docker-app"
  zip_file: $TRAVIS_BUILD_DIR/docker-app-$TRAVIS_BUILD_NUMBER.zip
  bucket_name: "elasticbeanstalk-eu-central-1-990322255852"
