sudo: required

language: bash

env:
  - APP=Gatsby

services:
  - docker

before_install:
  - docker build -t trooper1989/$APP-App -f ./App/$APP/Dockerfile.dev ./App/$APP

script:
  - docker run -e CI=true trooper1989/$APP-app npm test

before_deploy:
  - echo 'Zipping the app'
  - cd ./App/$APP && zip -r /$TRAVIS_BUILD_DIR/$APP-App-$TRAVIS_BUILD_NUMBER.zip *
  - echo 'Zipping finished'

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "eu-central-1"
  app: "docker-app"
  env: "docker-app-env"
  zip_file: /$TRAVIS_BUILD_DIR/$APP-app-$TRAVIS_BUILD_NUMBER.zip
  skip_cleanup: true
  bucket_name: "elasticbeanstalk-eu-central-1-451453809844"
